services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: npm run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.env
    ports:
      - "4000:3000"
    restart: always
    networks:
      - grpc-net
      - redis_net
    volumes:
      - .:/usr/src/app
      - ./proto/:/usr/src/proto
      - /usr/src/app/node_modules
  authentication:
    container_name: authentication
    build:
      context: .
      dockerfile: ./apps/authentication/Dockerfile
      target: development
    command: npm run start:dev authentication
    env_file:
      - ./apps/authentication/.env
    ports:
      - "50051:50051"
    depends_on:
      - mongo
    networks:
      - grpc-net
      - mongo-net
      - redis_net
    volumes:
      - .:/usr/src/app
      - ./proto/:/usr/src/proto
      - /usr/src/app/node_modules
  todo:
    container_name: todo
    build:
      context: .
      dockerfile: ./apps/todo/Dockerfile
      target: development
    command: npm run start:dev todo
    env_file:
      - ./apps/todo/.env
    ports:
      - "50052:50051"
      - "6006:6006"
    networks:
      - mongo-net
      - grpc-net
    volumes:
      - .:/usr/src/app
      - ./proto/:/usr/src/proto
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:5.0
    ports:
      - "127.0.0.1:27717:27017"
    networks:
      - mongo-net
    volumes:
      - 'mongo_data:/data/db'
  redis:
     container_name: redis
     image: redis
     restart: always
     ports:
      - '6379:6379'
     networks:
      - redis_net
  postgres:
    container_name: postgres
    image: postgres:12.7
    ports:
      - "5432:5432"
    networks:
      - postgres-net
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: mohamad
      POSTGRES_PASSWORD: hasan
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  
  

networks:
  mongo-net:
  redis_net:
  postgres-net:
  grpc-net:
volumes: 
  postgres_data:
  mongo_data: